refactor: upgrade Vue version and switch to Vite
SAP-samples/ui5-webcomponents-sample-vue pull request #84
Opened 2023-02-24 10:17 UTC by hinzzx

With this change we are migrating the Sample TODO Application configuration from **Vue 2** to **Vue 3**, as well as **`Vite`** integration to achieve better performance results.

For the process most of the time the steps described in the [Vue 3 Migration Guide](https://v3-migration.vuejs.org/)

 were followed.

2023-02-24 11:17 UTC, ilhan007 commented on src/main.js
> +import { createApp, h, configureCompat } from '@vue/compat';
It's seems `@vue/compat` is a migration package  provided by the vue team for smooth migration from `vue2` to `vue3`. But, I think we should generally change the app development to`vue3`

For example, in the docs we have: `createApp` from `@vue` package not from `@vue/compat`
<img width="756" alt="Screenshot 2023-02-24 at 13 14 03" src="https://user-images.githubusercontent.com/15702139/221165603-3b99dd2a-32d5-4431-b5f5-3f6e091020a6.png">

Perhaps we need to change other thing as well, but at the end the goal would be to follow the standard `vue3` app development mode as we just start creating this todo app from scratch.

2023-02-24 12:55 UTC, vladitasev requested changes

2023-02-24 12:55 UTC, vladitasev commented on vite.config.js
> +          // treat all tags with a ui5- as custom elements
with a "ui5-" prefix

2023-02-24 12:55 UTC, vladitasev commented on src/components/TodoItem.vue
> +  <ui5-li-custom :data-key="datakey" :selected="selected">
why was this changed?

2023-02-24 13:02 UTC, vladitasev reviewed
I also noticed, that the `readme.md` is outdated - it mentions code from the old version

2023-02-24 13:14 UTC, vladitasev reviewed
The app does not run correctly when I do `npm run start` (only `npm run dev` seems to work)

2023-02-25 15:40 UTC, ilhan007 commented on src/main.js
> +const app = createApp({
Could you try if the shortest setup will work for us:
```js
import { createApp } from 'vue'
import App from './App.vue'
createApp(App).mount('#app')
```

2023-02-25 15:49 UTC, ilhan007 commented on src/components/TodoList.vue
> +export default defineComponent({
[defineComponent](https://vuejs.org/guide/typescript/overview.html#definecomponent) seems to be recommended in TS mode. Maybe the simpler setup would work for us
```js
export default {
    components: {
        TodoItem
     },
     
```

2023-02-25 16:45 UTC, ilhan007 commented on package.json
>      "@ui5/webcomponents-icons": "^1.4.0",
@ui5/webcomponents-* deps could be also updated to latest (1.10.4)

2023-02-25 17:02 UTC, ilhan007 commented
You can also check if we still need Babel with Vite. Let's try if the app will continue working without:
- [babel.config.js](https://github.com/SAP-samples/ui5-webcomponents-sample-vue/blob/main/babel.config.js) file
-  and in the package.json 
```json
 "parserOptions": {
      "parser": "babel-eslint"
 }
```

```json
  "devDependencies": {
     "@babel/core": "^7.18.5",
     "@babel/eslint-parser": "^7.18.2",
     "@vue/cli-plugin-babel": "^5.0.4"
  }
```

2023-02-25 17:07 UTC, ilhan007 commented on package.json
> +    "@vue/compiler-sfc": "^3.2.47",
"@vue/compiler-sfc" - do we need this dependency

At least reading the package [readme](https://www.npmjs.com/package/@vue/compiler-sfc), it seems we can without it:
Note: as of 3.2.13+, this package is included as a dependency of the main vue package. This means you no longer need to explicitly install this package

2023-02-25 17:10 UTC, ilhan007 commented on package.json
> +    "vue-template-compiler": "^2.0.0"
[vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler) seems to be related with vue 2 (This package can be used to pre-compile Vue 2.0 templates..)

2023-02-25 17:12 UTC, ilhan007 commented on package.json
>      "file-loader": "^6.2.0",
`file-loader` was part of the webpack config (used to be described in the old readme ), but I believe we can run the app without it.

2023-02-25 17:16 UTC, ilhan007 commented on package.json
>      "@vue/cli-service": "^5.0.4",
`@vue/cli-service` https://cli.vuejs.org/guide/cli-service.html seems to be outdated as well.
The article starts with:
"Vue CLI is in Maintenance Mode!
For new projects, it is now recommended to use [create-vue](https://github.com/vuejs/create-vue) to scaffold [Vite](https://vitejs.dev/)-based projects. Also refer to the [Vue 3 Tooling Guide](https://vuejs.org/guide/scaling-up/tooling.html) for the latest recommendations."

2023-02-25 17:19 UTC, ilhan007 commented on package.json
>      "@vue/cli-service": "^5.0.4",
Unfortunately, it's used for the "lint" - if we don't find better option we have to keep it I guess.

2023-02-25 17:44 UTC, ilhan007 commented on README.md
> +To avoid issues, it is recommended to exclude our custom elements from component resolution by specifying `compilerOptions.isCustomElement` in our `vite.config` file.
I suggest removing "To avoid issues", as it sounds like there are some issues, while it's just an recommended config for optimisation.

"By default, Vue will attempt to resolve a non-native HTML tag as a registered Vue component before falling back to rendering it as a custom element. To let Vue know that certain elements should be treated as custom elements and skip component resolution, specify the `compilerOptions.isCustomElement` option in the `vite.config.js` file:"

2023-02-26 08:57 UTC, hinzzx commented on package.json
> +    "vue-template-compiler": "^2.0.0"
I had errors with installing Vite, and in order to fix it I had to install the vue-template-compiler@2.0.0. I think we wont need it anymore. Removing it.

2023-02-27 08:29 UTC, ilhan007 commented on package.json
> +    "@ui5/webcomponents": "1.10.4",
Better align the version of the ui5/* packages
- for the main package - 1.10.4 (exact version is set) 
- for some  - ^1.10.4, 
- for others - ^1.10.5.

2023-02-27 08:33 UTC, ilhan007 commented on package.json
> +      "plugin:vue/vue3-recommended"
I think `.eslintrc.js`file  already covers this. 
We need to use either `.eslintrc.js`file, or `eslintConfig` in the package.json, one of them is obsolete - let's stick to the  .eslintrc.js file as recommended practice for eslint config.

2023-02-27 08:34 UTC, ilhan007 commented on src/App.vue
> +import '@ui5/webcomponents-theming/dist/Assets.js'
Is there a reason for this new import - seems the app was working without it before.

2023-02-27 08:37 UTC, ilhan007 commented on src/App.vue
> +			if (typeof newlySelected === "undefined") {
`if (!newlySelected)` could be used and shorter, null or undefined, or another falsy value don't make change for the code after.

2023-02-27 09:26 UTC, ilhan007 commented on package.json
> +    "autoprefixer": "^10.4.13",
autoprefixer is newly added - is it a dependency we must have

2023-02-27 11:57 UTC, hinzzx commented on src/App.vue
> +import '@ui5/webcomponents-theming/dist/Assets.js'
After I updated the components, the theming button stopped working. And as a solution I imported this.

2023-02-27 12:02 UTC, hinzzx commented on package.json
> +    "autoprefixer": "^10.4.13",
It was needed ( at least on my machine ) in order to update the web components' version, since there was some postcss-p error. As I checked it works fine now, so I am removing it.

2023-02-28 09:30 UTC, ilhan007 commented on package.json
> +    "dev": "vite",
In vue3 setup, we now have only these 3 commands:
"dev": "vite",
"build": "vite build",
"preview": "vite preview"

- Remove:"start", "serve"
- Add "preview"

2023-02-28 11:19 UTC, vladitasev approved these changes

2023-02-28 13:00 UTC, merged